### PR TITLE
fix: vidstream -> vidplay

### PR DESCRIPTION
**Pull request by yashasnadigsyn**

### CODE REVIEW

**Comment by yashasnadigsyn** [comment]
I checked the website. It seems they changed vidstream to vidplay while getting vidstream_id

**Comment by justchokingaround** [comment]
yeah, you're right. do u mind changing the variables name's accordingly too please?

**Comment by yashasnadigsyn** [comment]
changed from vidstream_id to vidplay_id

**Comment by justchokingaround** [comment]
thx for the PR!

**Pull request merged**
